### ISSUE TITLE
[Bug] The json passed through the body does not parse

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [pactumjs/pactum-cucumber-boilerplate#1]
Hey there,
Currently, with reference to this boilerplate, I was writing some tests for my nodejs project and I found a problem with the presented example in this boilerplate.

### Given Example in current boilerplate
```js
Given(/I set body to/, function (body) {
  spec.withBody(body);
});
```
The above example generates an error as the `JSON` body passed to it while the `POST` request is not parsed and thus sends in a `404` error failing the tests.

### Example error message
```js
[W] Request
{
  "url": "http://localhost:3000/api/v1/users/signup",
  "method": "POST",
  "path": "/api/v1/users/signup",
  "body": "{\"name\": \"test\",\"email\": \"test@test.com\",\"password\": \"this is test\",\"passwordConfirm\": \"this is test\"}",
  "timeout": 3000
}
[W] Response
{
  "statusCode": 400,
  "headers": {
    "access-control-allow-origin": "*",
    "content-security-policy": "default-src 'self';base-uri 'self';block-all-mixed-content;font-src 'self' https: data:;frame-ancestors 'self';img-src 'self' data:;object-src 'none';script-src 'self';script-src-attr 'none';style-src 'self' https: 'unsafe-inline';upgrade-insecure-requests",
    "x-dns-prefetch-control": "off",
    "expect-ct": "max-age=0",
    "x-frame-options": "SAMEORIGIN",
    "strict-transport-security": "max-age=15552000; includeSubDomains",
    "x-download-options": "noopen",
    "x-content-type-options": "nosniff",
    "x-permitted-cross-domain-policies": "none",
    "referrer-policy": "no-referrer",
    "x-xss-protection": "0",
    "x-ratelimit-limit": "100",
    "x-ratelimit-remaining": "97",
    "date": "Fri, 26 Nov 2021 15:24:34 GMT",
    "x-ratelimit-reset": "1637943868",
    "content-type": "application/json; charset=utf-8",
    "content-length": "136",
    "etag": "W/\"88-/uNT+8avxEadGPJsOEqrvnrtc+Q\"",
    "vary": "Accept-Encoding",
    "connection": "close"
  },
  "body": {
    "status": "fail",
    "message": "User should have a name. User should have an email. Please provide a password. Please confirm the password"
  }
}

```

### Possible working solution
```js
Given(/I set body to/, function (body) {
  spec.withBody(JSON.parse(body));
});
```
This solves the error and passes all the tests which require sending `JSON` body data via `POST` request

#### If this helps I would like to work on it and raise PR related to it. :slightly_smiling_face:

**Comment by ASaiAnudeep** [comment]
Thanks for bringing this up @kaiwalyakoparkar 

Parsing all payloads to JSON might cause problems to other use cases. For example, posting a text payload. I think we should handle the non-JSON payloads in an elegant way.

There are couple of solutions I can think of.

1. Add a try catch block.

```js
Given(/I set body to/, function (body) {
  try {
    spec.withJson(JSON.parse(body));
  } catch(error) {
    spec.withBody(body);
  }
});
```

2. Add an independent step-definition for JSON payloads.

```js
Given(/I set body to a JSON/, function (body) {
    spec.withJson(JSON.parse(body));
});
```

I don't have any preference here. Could you please update the PR accordingly - #2  

#### Thanks for your contribution!

**Comment by kaiwalyakoparkar** [comment]
Hey @ASaiAnudeep, Thank you so much. I have made the required changes in the PR.
