### ISSUE TITLE
Toss will be called twice

### ISSUE THREAD

**Issue by eljefedelrodeodeljefe** [pactumjs/pactum-cucumber-boilerplate#3]
Hi, I believe the example here, will cause the Tosser to be called twice. https://github.com/pactumjs/pactum-cucumber-boilerplate/blob/267633c0c9451ad1c7bb26687fce092402f09a1e/features/support/steps.js#L47

This leads to multiple requests at the origin with for example two consequence:
- query params will be set twice, resulting in something around `/url?test=1?test=1`
- with form data bodies to be empty the second time around

only the second request will counted, which in the above examples will in some scenarios lead to unwanted results.

**Comment by ASaiAnudeep** [comment]
I'm not able to replicate the issue in my local. `toss` is being called only once and there are no duplicate query params as well.

Could you please provide us more details to look into it.
