### ISSUE TITLE
🙇🏻 npx integration

### ISSUE THREAD

**Issue by depapp** [pactumjs/pactum-cucumber-boilerplate#4]
hello @ASaiAnudeep @leelaprasadv @kaiwalyakoparkar 

[inspired](https://github.com/depapp/pusakatest#bookmark-credits) by this boilerplate, I've tried to integrate it with `npx`.
so people can easily setup this boilerplate on their local machine using (https://github.com/depapp/pusakatest)
```bash
npx pusakatest
``` 

also I've implement cucumber-bdd-localization into it.
![image](https://user-images.githubusercontent.com/6134774/186563548-90cba1c9-e514-48dc-9815-1718b425ceae.png)

thank you for the inspiration 🙇🏻

**Comment by ASaiAnudeep** [comment]
Thank you @depapp for building the cli tool. Please feel free to update the readme to include the command.

**Comment by depapp** [comment]
sure @ASaiAnudeep 🙇🏻

**Comment by depapp** [comment]
sure @ASaiAnudeep 🎊 
anyway, is there any requirement to join `PactumJS organization`? to be a member of this open source project 🙇🏻

**Comment by ASaiAnudeep** [comment]
We haven't defined any requirements as of now. We will get back to you.
